
// creating Error Handling using 
// try... throw... catchs

try {
    throw Error('Error occured');
  } catch (e)
  {
   console.log(e);
  }
  
  
  
  
  